spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gesclasse
    username: babaGM
    password: GalsenMedic123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
clients:
  filiere-url: http://localhost:8082/api/filieres
  niveau-url: http://localhost:8082/api/niveaux 
